import type { Metadata } from 'next';
import { Archivo, Space_Mono } from 'next/font/google';
import '@radix-ui/themes/styles.css';
import UITheme from '@/ui/providers/ThemeProvider';
import './globals.css';

const archivo = Archivo({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-archivo',
});

const space_mono = Space_Mono({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-space-mono',
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Qites',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${archivo.variable} ${space_mono.variable} dark antialiased`}
      >
        <UITheme accentColor="jade" grayColor="slate" radius="small">
          {children}
        </UITheme>
      </body>
    </html>
  );
}
